name: aqm-eval-dev
channels:
  - conda-forge
  - ufs-community # Needed for SRW context
  - nodefaults
dependencies:
  - awscli=2.28.*
  - pydantic=2.11.*
  - pydantic-settings=2.11.*
  - python=3.11
  - typer=0.16.*
  - dask=2024.2.1
  - melodies-monet=1.*
  - numpy=1.26.*
  - uwtools # Needed for SRW context
  # dev only from here
  - mypy=1.17.*
  - nco=5.3.*
  - polyfactory=2.22.*
  - pre-commit=4.3.*
  - pytest=8.4.*
  - pytest-mock=3.14.*
  - ruff=0.12.*
  - python-box=7.3.*
