name: aqm-eval
channels:
  - conda-forge
  - ufs-community # Needed for SRW context
  - nodefaults
dependencies:
  - awscli=2.28.*
  - pydantic=2.11.*
  - pydantic-settings=2.11.*
  - python=3.11
  - typer=0.16.*
  - dask=2024.2.1
  - melodies-monet=1.*
  - nccmp=1.10.*
  - numpy=1.26.*
  - uwtools=2.9.1 # Needed for SRW context
